# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for CodeAlive MCP Server
FROM python:3.11.15-slim-bookworm AS base

# MCP Server validation label for Docker registry
LABEL io.modelcontextprotocol.server.name="io.github.CodeAlive-AI/codealive-mcp"

# Version injected at build time for setuptools-scm
ARG VERSION=0.0.0
ENV SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION

# Set working directory
WORKDIR /app

# Install system dependencies for building and SSL
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy application code first
COPY . /app

# Install the locked runtime environment with the newest uv release older than
# seven days at release preparation time.
RUN python -m pip install --no-cache-dir "uv==0.11.28" \
    && uv sync --locked --no-dev

# Expose port for HTTP transport
EXPOSE 8000

# Default command: HTTP transport for containerized deployment
CMD ["/app/.venv/bin/python", "src/codealive_mcp_server.py", "--transport", "http", "--host", "0.0.0.0", "--port", "8000"]
