# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for CodeAlive MCP Server
FROM python:3.11-slim AS base

# Set working directory
WORKDIR /app

# Install system dependencies for building and SSL
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir \
    fastmcp>=2.0.0 \
    httpx>=0.26.0 \
    python-dotenv>=1.0.0

# Copy application code
COPY . /app

# Expose port for HTTP transport
EXPOSE 8000

# Default command: HTTP transport for containerized deployment
CMD ["python", "src/codealive_mcp_server.py", "--transport", "http", "--host", "0.0.0.0", "--port", "8000"]
