# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for CodeAlive MCP Server
FROM python:3.11-slim AS base

# Set working directory
WORKDIR /app

# Install system dependencies for building and SSL
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy application code first
COPY . /app

# Install the package using pyproject.toml
RUN pip install --no-cache-dir -e .

# Expose port for HTTP transport
EXPOSE 8000

# Default command: HTTP transport for containerized deployment
CMD ["python", "src/codealive_mcp_server.py", "--transport", "http", "--host", "0.0.0.0", "--port", "8000"]
